getporter/operator

- .dockerignore
- .github/workflows/build.yml
- .gitignore
- Makefile
- api/v1/installation_types.go
- config/crd/bases/porter.sh_installations.yaml
- config/manager/kustomization.yaml
- go.mod
- go.sum
- magefile.go
* Install mage properly on github actions agent
* Document targets
* Fix Bump target to always apply the local file
* Set Installation.agentConfig as optional, it was blocking Bump from working.
> Cleanup build scripts

- .github/workflows/build.yml
- Makefile
- api/v1/installation_types_test.go
- controllers/installation_test.go
- controllers/suite_test.go
- magefile.go
* Move makefile test -> magefile TestIntegration
* Do not run unit tests with integration tests
* Make pwd a function
* Deploy before intgration tests if needed
* Upload code coverage reports to codecov
> Improve tests

- .dockerignore
- Dockerfile
- magefile.go
Take advantage of mounting the go cache when building inside a container 🏎️ 💨
> Enable buildkit for controller builds

- .github/workflows/build.yml
- Makefile
- config/manager/kustomization.yaml
- installer/porter.yaml
- magefile.go
This adds a Porter bundle that installs the Porter Operator using the manifests generated by kustomize. I looked into how to use OLM and this will work fine for now instead.
> Install operator using manifests

- .github/workflows/build.yml
- config/manager/kustomization.yaml
- mage/env.go
- mage/git.go
- magefile.go
The heady days of camping on canary during dev are over.
> Start tagging releases on push

- installer/porter.yaml
https://github.com/getporter/porter/issues/1449
> Workaround porter bug

- README.md
- api/v1/agentconfig_types.go
- api/v1/agentconfig_types_test.go
- api/v1/installation_types.go
- config/crd/bases/porter.sh_agentconfigs.yaml
- config/crd/bases/porter.sh_installations.yaml
- controllers/installation_controller.go
- controllers/installation_test.go
- controllers/suite_test.go
- magefile.go
Adds implementation service account to agent config closes #16
> Implement Installation Service Account

- installer/porter.yaml
Updates the operator installer bundle to allow setting of installationServiceAccount
> Add installationserviceaccount to installer bundle

- docs/content/quickstart/_index.md
When we fixed the installation name in #50 we missed a few spots.
> Fix installation name in quickstart

- magefile.go
It was always reporting back undeployed.
~Requires #57 to be merged first because it fixes the build~
> Fix IsDeployed mage target

- docs/content/quickstart/_index.md
Add instructions for how to uninstall a bundle in the quickstart
> Include uninstall in the quickstart

- docs/content/install.md
- docs/content/quickstart/_index.md
Update the docs to use the most recent release of the operator.
> Do not use canary in the documentation

- .github/workflows/assign-to-project.yaml
When an issue or pull request is opened, automatically add it to our organization project board.
> Auto add issues and prs from this repo to our project board

- config/crd/bases/porter.sh_porterconfigs.yaml
> Update generated file now that default plugin is optional

- docs/content/_index.md
This updates our home page to remove the disclaimer about credential and parameter sets
> Cred and param sets are actually supported

- tests/integration/utils_test.go
Instead of using unstructured to get the resource status fetch it directly from the resource. This should remove a race condition where the resource status is out of sync with what is in k8s when immediately checking status of a resource after applying and waiting for it to complete
Tested locally, no failures across multiple runs of integration tests
> test: Updated waitForPorter utils test helper

- api/v1/const.go
- docs/content/file-formats.md
- docs/content/install.md
- docs/content/quickstart/_index.md
- magefiles/magefile.go
Update porter, and its mixins/plugins to the most recent v1 releases.
> Update porter and operator to the most recent releases

- installer/manifests/namespace/porter-agentconfig.yaml
I accidentally committed my test data into the upstream
> fix default value for default agent config

- .github/workflows/build.yml
CodeQL v1 is no longer supported.
> Update to CodeQL v2

- docs/content/install.md
- docs/content/quickstart/_index.md
Update the installation instructions for the operator to reference the latest version, v0.8.0
> Update installation instructions to v0.8.0

- .github/workflows/build.yml
Trigger a build when a tag starts with v, e.g. v1.2.3
> Trigger builds on tags

- mage/docs/docs.go
This removes the issues with go vet ./... and staticcheck ./... 
This issue was written against getporter/porter but to gain consistency and quality, doing this here as well [porter issue 2727](https://github.com/getporter/porter/issues/2727)
_No notes_
> Go vet and Staticcheck for go1.20 removed unused var 'must'
