getporter/operator

- config/rbac/agent_role.yaml
- installer/helpers.sh
- installer/porter.yaml
- magefile.go
* add rbac for pod/logs so they are viewable from the porter agent job
* use v0.28.3 of k8s mixin to get fix for uninstall, so it can be repeated
* Fix using local images from the operator, and other magefile tweaks
> Fix testing with a local porter agent

- config/rbac/agent_role.yaml
- magefile.go
When running in a local dev env, e.g. running from source, the cluster role was missing access to namespaces which is now required by the k8s storage plugin.
Also we were still using the locally built porter image, instead of the agent image we are now publishing with new porter builds.
> Fix local config

- Dockerfile
- config/manager/manager.yaml
- Opinionated changes to dockerfile -- specifically, using the `/app` folder as a workdir, and specifying the full path to the manager executable for the entrypoint directive
- Update golang build image from 1.15 tag to 1.17 to prevent building with a version of golang affected by CVE-2021-39293
> Opinionated Dockerfile && Golang Update

- .github/workflows/build.yml
- api/v1/agentconfig_types.go
- api/v1/agentconfig_types_test.go
- config/crd/bases/porter.sh_agentconfigs.yaml
- docs/content/file-formats.md
- go.mod
- go.sum
Do not use "latest" or "canary" when defaulting the porter-agent. We
don't want to encourage people to use mutable tags as it can easily
cause breakages when we release new versions.
We will bump this value each time we update the operator to work with a
new version of Porter instead. This is just for the default, so users
can always override it with an AgentConfig.
Fixes #51
> Pin the default porter-agent to a specific version

- controllers/installation_controller.go
- controllers/installation_controller_test.go
- docs/content/install.md
- docs/content/quickstart/_index.md
* Set fsGroup on porter agent pod
We had only tested our installation on KinD, which doesn't seem to have
the same file permissions on its default storage class. When we tried to
run the operator on Azure (AKS), we found that the agent couldn't write
to the mounted volume (/porter-shared).
The porter agent runs as nonroot, not root, as part of our hardening
process for IronBank. So when the volume is mounted, it needs to be
marked with the same user id for nonroot so that the container has
permission to write to the volume.
* Clarify which version of porter is required for operator
The operator (v0.3.0) requires porter v1.0.0-alpha.8+. Our docs had hard
coded a previous version in our installation commands which confused
users. I've added text that explains which version to use, and …
> Fixes for running operator on Azure (AKS)

- controllers/installation_controller.go
- controllers/installation_controller_test.go
- controllers/installation_test.go
- controllers/suite_test.go
- main.go
I had put in code to trigger reconcile when a job that we created changes, but it actually wasn't working.
* Only filter events for installations, so that jobs aren't filtered out
* Set the owner reference using the k8s library because I was doing it wrong. The controller flag wasn't also set.
> Reconcile when owned jobs change

- .github/workflows/build.yml
- CONTRIBUTING.md
- tests/integration/installation_test.go
The ginkgo tests often have to trigger the controller with a change, like editing an installation resource, and then wait for the controller to react and the resulting porter action jobs to finish.
Depending on if you already have the images pulled, and how fast your machine is, this can take a pretty variable amount of time. I've made the wait time configurable so that we can increase it on our CI build.
> Make test wait time configurable

- magefiles/magefile.go
Since porter now has the capability to detect bundle overwrite, we need to add the `--force` flag to push to the `latest` tag
> force publish to latest release tag 

- REVIEWING.md
- docs/content/install.md
- docs/content/quickstart/_index.md
now that the `v0.7.1` is published, we can update the doc to reflect that.
This PR also adds a REVIEWING.md to document our release process for the operator
> update doc to v0.7.1

- tests/integration/credset_test.go
- tests/integration/utils_test.go
This PR fixes a check in integration test to actually check for expected condition.
In the `credset_test.go`, we were not correctly checking for a failed installation and this PR fixes that.
When debug for a failed resource, the order of parameters were not passed in correctly, this PR fixes it.
> Check for failed condition in credential controller test

- Dockerfile
- go.mod
- go.sum
- netlify.toml
* Compile with Go 1.19.3. [CVE-2022-41716](https://github.com/advisories/GHSA-mh68-qf2j-8c5g) was reported in Go 1.18.6, so this updates to the most recently patched version of Go for our build.
* Bump emicklei/go-restful to v3.9.0. Twistlock identified that v0.3.8 of go-restful has a CVE. I couldn't find a report of it based on the identifier returned, PRISMA-2022-0227, but I'm hoping that updating to the most recent version of the package will make the Twistlock scanner happy.
> Fix CVE-2022-41716 and PRISMA-2022-0227

- Dockerfile
- netlify.toml
Updating to Go 1.19.4 because it contains security patches for two CVEs
https://go.dev/doc/devel/release#go1.19.4
1. CVE-2022-41720 and Go issue https://go.dev/issue/56694.
2. CVE-2022-41717 and Go issue https://go.dev/issue/56350.
> Update to go 1.19.4

- go.mod
- go.sum
This addresses PRISMA-2022-0227 which has no entry anywhere useful on the internet but is reported by IronBank. It has a fix for https://github.com/emicklei/go-restful/issues/497.
> Bump github.com/emicklei/go-restful to 3.10.1

- installer/vanilla.porter.yaml
mongodb helm chart no longer has 12.1.15 available. This PR updates it to 12.1.16
> update mongodb helm chart default version to v12.1.16

- api/v1/porterconfig_types.go
- config/crd/bases/getporter.org_porterconfigs.yaml
- config/samples/_v1_porterconfig.yaml
- docs/content/install.md
- installer/helpers.sh
In order for a user to be able to just copy/paste a Porter resource into the spec of the CRD and it just works, the naming for PorterConfig CRD needs to be updated from camel case to seperated by hyphen.
relates to: #124
> change porter config crd to use the same naming conventions as Porter

- docs/content/administrators/configure-porter-agent.md
This doc pages demonstrates some ways to configure porter agent for various use cases
> add administrators doc for configre porter agent

- controllers/agentconfig_controller.go
- controllers/agentconfig_controller_test.go
Sometimes, a test in our CI build randomly times out when trying to install a plugin. see the log here: https://github.com/getporter/operator/actions/runs/4116258618/jobs/7106066540
I found that it's due to a race condition if two AgentConfig reconcile requests comes in around the same time before a AgentAction is created for installing a plugin.
Currently, this will cause two empty temporary plugin persistent volume claims being created. Then the rename for the plugin pvc will never proceed.
This PR fix the check that determine whether a plugin volume already exists. 
_Put any questions or notes for the reviewer here._
> fix race condition to createEmptyPluginVolume

- .github/workflows/build.yml
- docker-bake.json
- magefiles/magefile.go
* Adding a final multi arch image build for arm and x86
* Added logic to final CI step supporting publish from a fork
CI changes only
Closes #155
My goal was not to change any existing test logic.  Some refactoring to the kind test env would
allow a `docker buildx bake` pattern to be used in more places.
> 155 support multiple architecture image publish

- config/samples/_v1_porterconfig.yaml
- docs/content/file-formats.md
When #142 changed the naming convention for the PorterConfig resource so that we can copy/paste between a porter config file and a PorterConfig resource, it missed a few bits of the documentation.
> Fix documentation for PorterConfig

- api/v1/agentconfig_types.go
- api/v1/const.go
- controllers/agentaction_controller.go
- controllers/agentaction_controller_test.go
When no plugins are specified by the AgentConfig, the plugins PVC will be an empty string and the PVC should not be mounted. I have updated the job creation logic to check if the PVC name is empty and skip mounting when no plugins are specified.
I have also updated the logging so that when we fail to create a job from an AgentAction, we log the job yaml (base64 encoded) so that we can troubleshoot better.
For context, this came up when I updated the k8s plugin to use the latest version of the operator. Since it wasn't specifying any plugins, the tests were all failing because none of the action action jobs could be created, due to the empty pvc name on the job.
Closes #165 
Depending on what @VinozzZ thinks about if we should default to the k8s plugin when nothing is specified, there may …
> Do not mount plugins pvc when none specified

- api/v1/agentconfig_types.go
- api/v1/agentconfig_types_test.go
- config/crd/bases/getporter.org_agentconfigs.yaml
- controllers/agentaction_controller.go
- controllers/agentconfig_controller.go
- docs/content/administrators/configure-porter-agent.md
Added ability to specify storage class name for volumes created by the Agent Config controller so that a proper storage class can be selected that supports the required capabilities 
Closes #167 
Tested this in both KinD and AKS. Should extend the integration tests for the operator to test in all supported clouds
> 167 plugin volume not about to be mounted into agent action job on aks

- .github/workflows/build.yml
Dependabot PRs use branches that exist on the upstream repository. This is causing the push event for the build workflow to trigger but since Dependabot is not trusted, the push (build) workflow always fails due to lack of access. I've updated the push event to only trigger for the main branch to avoid the dependabot PRs always being flagged as failed.
> Only trigger the push event for the main branch

- Dockerfile
- netlify.toml
This addresses multiple CVEs identified in older versions of Go 1.17.
CVE-2022-41725
Twistlock CVE
High
go-1.19.4
CVE-2022-41724
Twistlock CVE
High
go-1.19.4
CVE-2022-41723
Twistlock CVE
High
go-1.19.4
CVE-2023-24532
Twistlock CVE
Medium
go-1.19.4
Fixes #186
> Build with Go 1.19.7

- installer/Dockerfile.tmpl
Update the installer base image to use Debian stable instead of the default stretch. See https://github.com/getporter/porter/issues/2744 for context. Debian stretch is archived and using stable will ensure that the image can always build.
`mage build` fails because stretch is no longer available.
N/A
> Use debian stable instead of stretch

- controllers/agentconfig_controller.go
- controllers/agentconfig_controller_test.go
- tests/integration/agentconfig_test.go
Previously when a volume existed that already satisfied the agent config plugins hash we would only return the temp volume claim. In this scenario however the temp volume claim can have already been deleted so we would return "nil" when we found a ready volume claim only. 
Now the ready volume claim is returned if its found, otherwise the temp claim is returned if its found, or finally a new empty one is created.
Closes #169 
_Put any questions or notes for the reviewer here._
renamePluginVolume handles reconciling if the volume claim is the ready or temp claim. This scenario is just for resolving at action create time if a final claim (ready) exists, a temp claim exists, or if a new claim needs to be created. …
> 169 porter operator manager unable to create agent actions if agent config is overwritten

- api/v1/agentaction_types.go
- api/v1/credentialset_types.go
- api/v1/credentialset_types_test.go
- api/v1/installation_types.go
- api/v1/parameterset_types.go
- api/v1/parameterset_types_test.go
- api/v1/zz_generated.deepcopy.go
- config/crd/bases/getporter.org_agentactions.yaml
- config/crd/bases/getporter.org_agentconfigs.yaml
- config/crd/bases/getporter.org_credentialsets.yaml
- config/crd/bases/getporter.org_installations.yaml
- config/crd/bases/getporter.org_parametersets.yaml
- controllers/agentaction_controller.go
- controllers/credentialset_controller.go
- controllers/credentialset_controller_test.go
- controllers/installation_controller.go
- controllers/installation_controller_test.go
- controllers/parameterset_controller.go
- controllers/parameterset_controller_test.go
- docs/content/_index.md
- docs/content/administrators/configure-porter-agent.md
- docs/content/file-formats.md
- docs/content/install.md
- mage/env.go
Remove the PorterConfig setting from individual resources so that the PorterConfig within any namespace is constant. This allows us to run a porter data service in each namespace and safely work with any resources defined in that namespace.
Fixes #154
I was running into build errors because PORTER_OPERATOR_REGISTRY was not set, it really shouldn't be required just to do a build, so I defaulted it to the local registry that mage sets up when it runs the tests, localhost:5000.
> Limit PorterConfig to namespace and system configuration 

- api/v1/installation_types.go
- config/crd/bases/getporter.org_installations.yaml
This adds additional printer columns to the installation custom resource definition
Closes #47 
_None_
> Add additional printer columns to installtion CRD

- controllers/agentconfig_controller.go
- controllers/agentconfig_controller_test.go
No issue to close but improves the testing posture of this controller. 
During adding these tests, there is a condition I believe we are not checking for.  If the list of PVCs returned length is < 1 we still continue to return the `readyPVC, tempPVC, nil` (`r.getExistingPluginPVCs(...)`).  There is a no-op check there for the items list but we are returning:
```go
return readyPVC, tempPVC, nil
```
even if the list (which doesn't error, because you can return an empty list) results.Items < 1.  Not sure what behavior we want from this but guarding against that was noted during testing this method. If we do want to make sure that we always get a list > 1 from that method, I can update this PR to modify that.  
- No, it's not needed for adding tests 
- No, no changes to the API was made …
> Create tests for method `renamePluginVolume`

- go.mod
- go.sum
Updates gomega and testify to requisite dependabot versions.
_Dependabot was downgrading controller-runtime to `v0.1.4.5` but we already upgraded to_ `v0.15.0`
Closes 
#222 
#223
> Update deps without downgrading controller-runtime

- .github/workflows/build.yml
- go.mod
- go.sum
Updates sync to 0.3.0 without downgrading controller-runtime to 0.14.6
Closes #216 
`None`
> Updates sync to 0.3.0 without downgrading controller-runtime

- api/v1/installation_types.go
- config/crd/bases/getporter.org_installations.yaml
Printer columns were printing out like this:
```python
NAME                            PORTER NAME    PORTER NAMESPACE   LAST ACTION     LAST STATUS   AGE
test-install-1691504789-nf9k2                                                                 6h39m
```
Now they print out like this:
```python
NAME                            PORTER NAME               PORTER NAMESPACE   LAST ACTION                           LAST STATUS   AGE
test-install-1691504789-nf9k2   test-install-1691504789   demo               test-install-1691504789-nf9k2-gnfm7   Succeeded     6h39m
```
The capital letters in the printcolumns kubebuilder annotation didn't allow them to be printed properly
No issue filed
`None`
> fix printer columns

- .github/CODEOWNERS
- netlify.toml
Changes the go version to 1.20.7 to build with netlify 
cleanup 
`None`
> Update netflify to build with 1.20.7

- controllers/agentaction_controller.go
- controllers/agentaction_controller_test.go
- controllers/agentconfig_controller.go
- controllers/agentconfig_controller_test.go
- controllers/credentialset_controller.go
- controllers/credentialset_controller_test.go
- controllers/installation_controller.go
- controllers/installation_controller_test.go
- controllers/parameterset_controller.go
- controllers/parameterset_controller_test.go
- tests/integration/suite_test.go
_This is for testing purposes_
> Use SetControllerReference from controllerutil

- controllers/installation_controller.go
- controllers/installation_controller_test.go
- controllers/parameterset_controller_test.go
- controllers/porter_resource_test.go
- main.go
- tests/integration/suite_test.go
Adds events to the installation controller when installation outputs get created and/or finish reconciling 
It doesn't.  It helps the user see events in the k8s context. 
_Slight enhancement but nothing to 😍 about_
> Utilize the Recorder to create events with installation resources

- docs/content/_index.md
- docs/content/administrators/configure-porter-agent.md
- docs/content/file-formats.md
- docs/content/glossary.md
- docs/content/install.md
- docs/content/quickstart/_index.md
Change and fix some broken links in the documentation to ensure the link checker can detect broken links in the future. 
Related to https://github.com/getporter/porter/pull/3027
> Fix links on in the documentation

- api/v1/installation_types.go
- controllers/installation_controller.go
- controllers/installation_controller_test.go
This will add the annotation that we will use to determine how we **want** to delete the resources (installations and otherwise) to adopt the pattern from cross-plane as noted in issue #297 
_~~This is still in draft~~_
All this does is just add the annotation, the WIP will use this to implement the logic behind this new annotation.
Partially closes #297 
_Put any questions or notes for the reviewer here._
> Add deletion policy annotation on all installations 

- controllers/installation_controller.go
- controllers/installation_controller_test.go
This allows deletion with uninstall and deletion with "orphan" by way of deletion policy.  
#297 again 
_Put any questions or notes for the reviewer here._
> Delete without uninstall

- go.mod
- go.sum
During the last release of Porter Core there was an issue where the pipeline published the canary version instead of the finalized released. This happens because the build scripts calculate the version incorrectly when multiple tags are present on the same commit.
The release process of the operator is slightly different, but updating the magefiles dependencies should ensure that the same issue is not appearing when the operator is released.
> Calculate the version correctly when releasing from tag
